dogpack/config/routes.rb
Dogpack::Application.routes.draw do

  devise_for :users

  root :to => "users#current"
    
  match '/search' => "search#search",         :as => :search
     
  resources :users, :meetups, :friendships
  
  resources :meetups do
    resources :reviews
  end

end

dogpack/app/models/meetup.rb
class Meetup < ActiveRecord::Base
  attr_accessible :sender_id, :recipient_id, :date, :venue, :message, :accept_status, :prev_meetup_id

  has_many :reviews
  
  belongs_to :recipient, :class_name => 'User', :foreign_key => 'recipient_id'
  belongs_to :sender, :class_name => 'User', :foreign_key => 'sender_id'
  
  belongs_to :previous_meetup, :class_name => 'Meetup', :foreign_key => ':prev_meetup_id'
  
  def has_reviewed(user)
    return self.reviews.where("reviewer_id = #{user.id}").count > 0
  end
  
  def other(user)
    return self.sender_id == user.id ? self.recipient : self.sender
  end

end

dogpack/app/controllers/meetups_controller.rb
class MeetupsController < ApplicationController
  
   before_filter :authenticate_user!
   
  # GET /meetups
  # def index
    # @meetups = Meetup.all
# 
    # respond_to do |format|
      # format.html # index.html.erb
    # end
  # end

  # # GET /meetups/1
  # def show
    # @meetup = Meetup.find(params[:id])
#     
    # respond_to do |format|
      # format.html # show.html.erb
    # end
  # end

  # GET /meetups/new
  def new
    @meetup = Meetup.new
    @recipient = User.find_by_id(params[:recipient_id])
    
    @recipient_meetups = []
    @recipient.upcoming_meetups.each do |m|
      @recipient_meetups.push({:title=> @recipient.name, :start=> m.date.strftime('%m-%d-%Y %H:%M:%S'), :end=> (m.date + 1.hour).strftime('%m-%d-%Y %H:%M:%S'), :allDay=> false})
    end
    
    @my_meetups = []
    current_user.upcoming_meetups.each do |m|
      @my_meetups.push({:title=> current_user.name, :start=> m.date.strftime('%m-%d-%Y %H:%M:%S'), :end=> (m.date + 1.hour).strftime('%m-%d-%Y %H:%M:%S'), :allDay=> false})
    end

    gon.recipient = @recipient
    gon.me = current_user
    gon.recipient_meetups = @recipient_meetups
    gon.my_meetups = @my_meetups
    
    @current_user = current_user
    @prev_meetup_id = params[:prev_meetup_id]
    
    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /meetups/1/edit
  def edit
    @meetup = Meetup.find(params[:id])
    @meetups = Meetup.all(:conditions => ["DATE(date) = DATE(?) AND (sender_id = ? OR recipient_id = ?) AND accept_status = 1", @meetup.date, current_user.id, current_user.id])
    @current_user = current_user;
    @sender = @meetup.other(@current_user)
  end

  # POST /meetups
  def create
    @meetup = Meetup.new(params[:meetup])
    @meetup.date = Time.at(params[:meetup][:date].to_i)
    
    respond_to do |format|
      if @meetup.save
       if(@meetup.prev_meetup_id.nil? )
          response = "An invitation to meetup with #{@meetup.recipient.name} was sent"
        else
          prev = Meetup.find(@meetup.prev_meetup_id)
          prev.accept_status = -1
          prev.save
          response = "A request to reschedule your meetup with #{@meetup.other(current_user).name} was sent"
        end
        format.html { redirect_to "/", notice: response }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /meetups/1
  def update
    @meetup = Meetup.find(params[:id])
    action = params[:commit]
    
    if action == "Reject" || action == "Cancel" 
      @meetup.accept_status = -1;
      if action == "Reject"
        response = "The invitation from #{@meetup.sender.name} was rejected"
      else
        response = "Your meetup with #{@meetup.other(current_user).name} was cancelled"
      end
    else
      @meetup.accept_status = 1;
      response = "The invitation from #{@meetup.sender.name} was accepted"
    end

    respond_to do |format|
      if @meetup.save
        format.html { redirect_to "/", notice: response }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /meetups/1
  def destroy
    @meetup = Meetup.find(params[:id])
    @meetup.destroy

    respond_to do |format|
      format.html { redirect_to meetups_url }
    end
  end
end

dogpack/app/helpers/meetups_helper.rb
module MeetupsHelper
end

dogpack/app/views/meetups/_form.html.erb
<%= form_for(@meetup) do |f| %>
  <% if @meetup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meetup.errors.count, "error") %> prohibited this meetup from being saved:</h2>

      <ul>
      <% @meetup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

dogpack/app/views/meetups/edit.html.erb
<div class="main-body container">
	<div class="row-fluid content-header">
		<div class="span12">
			<% if @meetup.accept_status == 0 %>
			<span class="lead header-text"><span class="username"><%= @sender.name%></span> has sent you an invitiation!</span>
			<% else %>
			<span class="lead header-text">Your meetup with <span class="username"><%= @sender.name%></span></span>
			<%end%>
		</div>
	</div>
	<div class="row-fluid content-row">
		<div class="span4">
    	<img id="profilePicture" class="profile-picture img-polaroid grid-photo" src="<%= @sender.image_url%>">
		</div>
		<div class="span8 lead">
      <div class="row-fluid">
      	<span class="span2"><i>When:</i></span>
      	<span class="span6" id="date"><%= @meetup.date.strftime '%b %e, %l:%M %p' %></span>
      </div>
      <div class="row-fluid">
      	<span class="span2"><i>Where:</i></span>
      	<span class="span6"><%= @meetup.venue %></span>
      </div>
			<div class="row-fluid">
				<span class="span2"><i>Message:</i></span>
				<span class="span6"><%= @meetup.message %></span>
			</div>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span12">
			<span class="lead"> Schedule for <%= @meetup.date.strftime '%b %e' %></span>
			<div class="row-fluid">
				<div class="span12 hero-unit">
					<% if @meetups.count == 0 %>
					<span>Nothing scheduled for that day</span>
					<% else %>
						<ul list="availabilityList">
						<% @meetups.each do |m| %>
						<li>Meeting with <%= m.other(current_user).name %> on <%= m.date.strftime '%b %e, %l:%M %p'%></li>
						<%end%>
						</ul>
					<%end%>
				</div>
			</div>
		</div>
	</div>
	<div class="row-fluid content-footer">
		<%= form_for @meetup, :url => { :action => 'update' } do |f| %>
		<div class="span12 btn-toolbar">
			<input type="hidden" name="meetup[accept_status]" value="-1" />
			<% if @meetup.accept_status == 0 %>
			<%= f.submit "Reject" , :class =>"btn btn-danger btn-large"%>
			<%= f.submit "Accept" , :class =>"btn btn-success btn-large"%>
			<% else %>
			<%= f.submit "Cancel" , :class =>"btn btn-danger btn-large"%>
			<% end%>
			<a class="btn btn-warning btn-large" href="/meetups/new?recipient_id=<%= @sender.id%>&prev_meetup_id=<%=@meetup.id%>">Reschedule</a>
		</div>
		<%end%>
	</div>
</div>

dogpack/app/views/meetups/index.html.erb
<h1>Listing meetups</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @meetups.each do |meetup| %>
  <tr>
    <td><%= link_to 'Show', meetup %></td>
    <td><%= link_to 'Edit', edit_meetup_path(meetup) %></td>
    <td><%= link_to 'Destroy', meetup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Meetup', new_meetup_path %>

dogpack/app/views/meetups/new.html.erb
<script type="text/javascript" src="/assets/fullcalendar.min.js"></script>
<script type="text/javascript" src="/assets/meetups.js"></script>
</script>
<div class="main-body container">
	<div class="row-fluid content-header">
	  <div class="span10">
	  	<% if @prev_meetup_id.nil?%>
	 	 		<span class="lead header-text">Schedule a meetup with <span class="username"><%= @recipient.name %></span></span>
	  	<% else %>
	  		<span class="lead header-text">Reschedule your meetup with <span class="username"><%= @recipient.name %></span></span>
	  		</br></br><span class="lead"><i>Meetup was previously scheduled for: <%= Meetup.find(@prev_meetup_id).date.strftime '%b %e, %l:%M %p' %></i></span>
	  	<% end %>
		</div>
		<div class="span2">
		  <img id="dog-photo" src="<%= @recipient.image_url %>" class="img-polaroid img-thumb pull-right"> 
		</div>
	</div>
	<div class="row-fluid content-body">                    
    <div class="span12">
      	<div id="calendar"></div>
		 </div>
	</div>
  <div class="row-fluid content-footer">
  	<div class="row-fluid content-row">
  		<div class="span12">
    		<span class="label">Info :</span> Indicates busy timeslots.
    	</div>
    </div>
    <div class="row-fluid">
    	<%= form_for @meetup, :html => {:id => 'meetupForm'},  :url => { :action => 'create' } do |f| %>
    	<input type="hidden" name="meetup[recipient_id]" value="<%= @recipient.id %>"  />
    	<input type="hidden" name="meetup[sender_id]" value="<%= @current_user.id %>" />
    	<input type="hidden" name="meetup[prev_meetup_id]" value="<%= @prev_meetup_id %>" />
    	<input type="hidden" name="meetup[accept_status]" value="0" />
    	<input id="hiddenTime" type="hidden" name="meetup[date]" />
   		<div class="row-fluid">
          <div class="span6">
          	<div class="row-fluid">
	            <div class="span4">
	                <span class="lead">Time :</span>
	            </div>
							<input  class="span8" name="meetup[date]" type="text" placeholder="Select a time slot in the calendar" id="inputMeetupTime" disabled>
            </div>
            <div class="row-fluid">
                <div class="span4">
                    <span class="lead">Location :</span>
                </div>
                <input class="span8" name="meetup[venue]" type="text" id="inputLocation" autocomplete="off" data-provide="typeahead" placeholder="Enter an address here...">
            </div>					
          </div>
          <div class="span6">
              <span class="lead">Message : </span>
              <%= f.text_area :message, :class => "span12", :rows=> "5", :placeholder => "Enter your message here" %>
              <!-- <textarea id="textAreaMessage" class="span12" rows="5" placeholder="Enter your message here..."></textarea> -->
          </div>
      </div>
			<div class="row-fluid">
				 <div class="span12 btn-toolbar">
				 <%= f.submit "Send" , :class =>"btn btn-success pull-right form-btn"%>
				 <a onclick="goBack()" id="cancelBtn-phone" class="btn btn-danger pull-right form-btn">Cancel</a>	
				 </div>				
			</div>
     <%end%>
 		</div>
 	</div>
</div>

dogpack/app/views/meetups/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_meetup_path(@meetup) %> |
<%= link_to 'Back', meetups_path %>