dogpack/config/routes.rb
Dogpack::Application.routes.draw do

  devise_for :users

  root :to => "users#current"
    
  match '/search' => "search#search",         :as => :search
     
  resources :users, :meetups, :friendships
  
  resources :meetups do
    resources :reviews
  end

end

dogpack/app/models/friendship.rb
class Friendship < ActiveRecord::Base
  attr_accessible :user_id, :friend_id
  
end

dogpack/app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  # GET /friendships
  # GET /friendships.json
  def index
    @friendships = Friendship.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @friendships }
    end
  end

  # GET /friendships/1
  # GET /friendships/1.json
  def show
    @friendship = Friendship.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @friendship }
    end
  end

  # GET /friendships/new
  # GET /friendships/new.json
  def new
    @friendship = Friendship.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @friendship }
    end
  end

  # GET /friendships/1/edit
  def edit
    @friendship = Friendship.find(params[:id])
  end

  # POST /friendships
  # POST /friendships.json
  def create
    @friendship = Friendship.new(params[:friendship])

    respond_to do |format|
      if @friendship.save
        format.html { redirect_to @friendship, notice: 'Friendship was successfully created.' }
        format.json { render json: @friendship, status: :created, location: @friendship }
      else
        format.html { render action: "new" }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /friendships/1
  # PUT /friendships/1.json
  def update
    @friendship = Friendship.find(params[:id])

    respond_to do |format|
      if @friendship.update_attributes(params[:friendship])
        format.html { redirect_to @friendship, notice: 'Friendship was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friendships/1
  # DELETE /friendships/1.json
  def destroy
    @friendship = Friendship.find(params[:id])
    @friendship.destroy

    respond_to do |format|
      format.html { redirect_to friendships_url }
      format.json { head :no_content }
    end
  end
end

dogpack/app/helpers/friendships_helper.rb
module FriendshipsHelper
end

dogpack/app/views/friendships/_form.html.erb
<%= form_for(@friendship) do |f| %>
  <% if @friendship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friendship.errors.count, "error") %> prohibited this friendship from being saved:</h2>

      <ul>
      <% @friendship.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

dogpack/app/views/friendships/edit.html.erb
<h1>Editing friendship</h1>

<%= render 'form' %>

<%= link_to 'Show', @friendship %> |
<%= link_to 'Back', friendships_path %>

dogpack/app/views/friendships/index.html.erb
<div class="main-body container">
	<div class="row-fluid content-header">
		<div class="span12">
			<span class="lead header-text">Friends</span>
		</div>
	</div>
	<div class="row-fluid content-body">
		<% User.where("").order("name").each_with_index do |u, i| %>
		<% if i % 3 == 0 %>
		<div class="row-fluid">
		<% end %>
			<div id="dog1" class="span4 row-fluid">
				<div class="span2"></div>
				<div class="span8">
					<a href="/users/<%= u.id %>"><img class="grid-photo img-polaroid" src="<%= u.image_url %>"></img></a>
					<div class="row-fluid">
						<div class="span5 lead username"><a href="/users/<%= u.id %>"><%= u.name %></a></div>
						<div class="span2"></div>
						<div class="span5 lead"><a class="btn btn-small btn-primary" href="/meetups/new?recipient_id=<%= u.id %>">Meetup!</a></div>
					</div>
				</div>
				<div class="span2"></div>
			</div>
		<% if i % 3 == 2 %>
		</div>
		<% end %>
		<% end %>
	</div>
</div>

dogpack/app/views/friendships/new.html.erb
<h1>New friendship</h1>

<%= render 'form' %>

<%= link_to 'Back', friendships_path %>

dogpack/app/views/friendships/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_friendship_path(@friendship) %> |
<%= link_to 'Back', friendships_path %>